# Generated by Django 3.2 on 2021-04-30 18:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vwap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open_dt', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('exchange', models.CharField(max_length=256)),
                ('volume', models.FloatField()),
                ('price_time', models.DateTimeField(blank=True, null=True)),
                ('vwap', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vwap_offset.pair')),
            ],
            options={
                'unique_together': {('pair', 'price_time')},
            },
        ),
    ]
