# Generated by Django 3.2.2 on 2021-05-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vwap_offset', '0003_auto_20210514_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
